project:
  output-dir: _output
  type: website
  render:
    - "*.qmd"

website:
  title : "Report"
  sidebar:
    contents:
      - section: "Algorithms"
        contents:
          - simplexe.qmd
          - nash_equilibrium.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    theme: cosmo
    toc: true