project:
  output-dir: _output
  type: book

book:
  title : "Report - Algorithmic Project IFEBY270"
  chapters:
    - index.qmd
    - simplexe.qmd
    - nash_equilibrium.qmd
    - knapsac.qmd

format:
  html:
    theme: cosmos
    # cosmos, darkly, sandstone, sketchy
    toc: true
    number-sections: true
  pdf:
    theme: cosmo
    title: "Report_Algorithmic_Project_IFEBY270"
    toc: true